version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./vector_db:/app/vector_db
    depends_on:
      - chroma

  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - ./vector_db:/chroma_db

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
    volumes:
      - ~/.n8n:/home/node/.n8n
    restart: unless-stopped
