# pdf_generator/pdf_generator.py
from fpdf import FPDF
import json
import os
from datetime import datetime

def generate_pdf(itinerary_data, output_path=None, logo_path="pdf_generator/static/logo.png"):
    """
    Generate a travel itinerary PDF using FPDF2
    """
    if not output_path:
        city = itinerary_data.get("city", "Travel")
        output_path = f"output/{city.lower()}_itinerary.pdf"

    # Create output folder
    os.makedirs("output", exist_ok=True)

    # Initialize PDF
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", "B", 16)

    # Header
    if os.path.exists(logo_path):
        pdf.image(logo_path, x=10, y=10, w=33)
        pdf.cell(0, 10, "", ln=True)  # Spacer for logo
        pdf.set_y(20)

    pdf.cell(0, 10, f"✈️ Trip to {itinerary_data['city']}", ln=True, align='C')
    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 10, f"Duration: {itinerary_data['days']} days", ln=True, align='C')
    pdf.cell(0, 10, f"Interests: {itinerary_data['preferences']}", ln=True, align='C')
    pdf.ln(10)

    # Itinerary
    for day_plan in itinerary_data.get("itinerary", []):
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, f"📅 Day {day_plan['day']}", ln=True)
        pdf.set_font("Arial", "", 12)

        for act in day_plan["schedule"]:
            pdf.set_font("Arial", "B", 12)
            pdf.cell(0, 8, f"{act['time']}: {act['activity']}", ln=True)
            pdf.set_font("Arial", "", 11)
            pdf.cell(0, 8, f"📍 {act['location']}", ln=True)
            if act.get("notes"):
                pdf.set_font("Arial", "I", 10)
                pdf.cell(0, 8, f"💡 {act['notes']}", ln=True)
                pdf.set_font("Arial", "", 11)
            pdf.ln(2)
        pdf.ln(8)

    # Recommendations
    if itinerary_data.get("recommendations"):
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "🌟 Recommendations", ln=True)
        pdf.set_font("Arial", "", 12)
        for rec in itinerary_data["recommendations"]:
            pdf.cell(0, 8, f"• {rec}", ln=True)
        pdf.ln(10)

    # Tips
    if itinerary_data.get("tips"):
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "💡 Travel Tips", ln=True)
        pdf.set_font("Arial", "", 12)
        for tip in itinerary_data["tips"]:
            pdf.cell(0, 8, f"• {tip}", ln=True)
        pdf.ln(10)

    # Footer
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 10, "Generated by TripGenie AI • Safe travels!", ln=True, align='C')

    # Save
    pdf.output(output_path)
    print(f"✅ PDF generated: {output_path}")
    return output_path

# CLI Usage: python pdf_generator.py plan.json
if __name__ == "__main__":
    import sys
    if len(sys.argv) != 2:
        print("Usage: python pdf_generator.py <itinerary_json_file>")
        sys.exit(1)

    with open(sys.argv[1], "r") as f:
        data = json.load(f)

    if "data" in 
        data = data["data"]

    generate_pdf(data)
